[package]
name = "battleships"
type = "contract"
authors = [""]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.1", directory="noir-projects/aztec-nr/aztec" }