[package]
name = "battleships"
type = "contract"
authors = ["Nicolas Chamo"]
compiler_version = ">=0.25.0"
description = "A fully-private implementation of Battleships using Aztec.nr and Noir with zero-knowledge proofs"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.1", directory="noir-projects/aztec-nr/aztec" }
uint_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.1", directory="noir-projects/aztec-nr/uint-note" }
address_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.1", directory="noir-projects/aztec-nr/address-note" }